### ISSUE TITLE
Upgrade SQLx

### ISSUE THREAD

**Issue by jamesjmeyer210** [jamesjmeyer210/actix_sqlx_mysql_user_crud#1]
SQLx has changed, in particular the numerical result types, so this repo needs to follow suit.

**Comment by jamesjmeyer210** [comment]
The core application now compiles. Now I have the following tasks:
 - [ ] Fix the runtime
 - [ ] Update the tests to reflect the new type usage
 - [ ] Implement the TODOs
 - [ ] Remove commented code

**Comment by jamesjmeyer210** [comment]
Placing this on hold.

Currently, my version of `actix-web` is running on 3. Version 3 is on tokio 0.3.*. I'll need for Actix to be on tokio 1.0.0, which means I need to wait for the release of Actix 4.

**Comment by jamesjmeyer210** [comment]
It looks like `actix-web` is on [4.0 now](https://github.com/actix/actix-web/releases/tag/web-v4.0.0-rc.1). I'll be able to proceed with the upgrade shortly.

**Comment by dkatz23238** [comment]
Thanks for your extremely detailed response, the c# stuff was quite definitely a clarifier as I did not what abstractions/philosophy you where using our basing yourself on.

Regarding potentially updating to update sqlx constructs, updating to actix 4,  curl tests, documentation, doubts about phantom types I'll get back to you via email for further discussion.

**Comment by jamesjmeyer210** [comment]
This task has been completed in [this PR](https://github.com/jamesjmeyer210/actix_sqlx_mysql_user_crud/pull/5).
