### ISSUE TITLE
post fail

### ISSUE THREAD

**Issue by chenyangguang** [jamesjmeyer210/actix_sqlx_mysql_user_crud#3]
Can't send post request success.

**Comment by jamesjmeyer210** [comment]
Can you elaborate on the specific post request that is failing?

**Comment by chenyangguang** [comment]
method; POST 

route: /group 

`
{
"name": "gitvim"
}
`

**Comment by jamesjmeyer210** [comment]
If you take a closer look at the source code, you'll see that the `POST group` endpoint accepts a `string`:

```rust
#[post("/group")]
async fn post_group(
    group: web::Json<String>,
    app_state: web::Data<AppState<'_>>,
) -> impl Responder {
// ...snip...
}
```

So instead of providing a JSON object, just provide a string:
```bash
curl --location --request POST 'http://localhost:8000/group' \
--header 'Content-Type: application/json' \
--data-raw '"abc"'
```

You can import this curl directly into postman.
